title: GbrG Academy
email: budhramgurung@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Get taught through the skilled trainers who gained experiences through
  real-world experiences.
brand_line: >-
  Revolutionizing the Learning Approach
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

permalink: /blogs/:title
future: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

